services:
  mysql:
    container_name: mysql
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ai-food
      MYSQL_USER: root
      MYSQL_PASSWORD:
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
    command: --default-authentication-plugin=mysql_native_password
    networks:
      - NUTRITION_TRACNKER-network

networks:
  NUTRITION_TRACNKER-network:
    driver: bridge